### ISSUE TITLE
Can't build master branch

### ISSUE THREAD

**Issue by martijn-heil** [SignalK/freeboard-sk#103]
After following the instructions:
```
git clone https://github.com/SignalK/freeboard-sk
cd freeboard-sk
npm i -g @angular/cli@latest
npm i
```
I get the following error;
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @signalk/freeboard-sk@1.17.0
npm ERR! Found: jasmine-core@3.6.0
npm ERR! node_modules/jasmine-core
npm ERR!   dev jasmine-core@"~3.6.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.8" from karma-jasmine-html-reporter@1.7.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR!   dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/martijn/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/martijn/.npm/_logs/2021-08-11T16_42_33_613Z-debug.log
```
When I subsequently do a `npm i --force` I get further errors related to signalk-client-angular and signalk-worker-angular;
```
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: jasmine-core@3.6.0
npm WARN node_modules/jasmine-core
npm WARN   dev jasmine-core@"~3.6.0" from the root project
npm WARN   1 more (karma-jasmine)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer jasmine-core@">=3.8" from karma-jasmine-html-reporter@1.7.0
npm WARN node_modules/karma-jasmine-html-reporter
npm WARN   dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @panaaj/signalk-client-angular@undefined
npm WARN node_modules/@panaaj/signalk-client-angular
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer @panaaj/signalk-client-angular@"^1.8.0" from signalk-worker-angular@1.1.2
npm WARN node_modules/signalk-worker-angular
npm WARN   dev signalk-worker-angular@"^1.1.2" from the root project
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@panaaj%2fsignalk-client-angular - Not found
npm ERR! 404 
npm ERR! 404  '@panaaj/signalk-client-angular@^1.8.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/martijn/.npm/_logs/2021-08-11T16_47_21_126Z-debug.log
```

**Comment by panaaj** [comment]
I have just repeated your steps with no issue (twice).
Not sure why the error log shows a dependency with signalk-client-angular@1.8.0 (that version is deprecated) and the package.json file has ^1.8.2..... which is the latest.

**Comment by martijn-heil** [comment]
@panaaj Strange, have you tried this in a clean, fresh environment? I get this error doing it on my Raspberry Pi, which is almost a brand new Arch Linux install with the only prior usage of NPM being a Signal K install with some plugins.

**Comment by panaaj** [comment]
Yes.. started from a new clone... on my laptop (only device I have with resources to build the project).
Note v1.17.0 is now published to NPM.

**Comment by martijn-heil** [comment]
@panaaj Could it perhaps be that your global npm environment and/or cache is preventing the error from showing up? When I get home in a week or so I'll try building it on my home desktop pc to see whether the error persists. In the meantime I'll try some things over here to figure it out, maybe there's something wrong with my system specifically.

**Comment by panaaj** [comment]
Is this still an issue for you or can this be closed?

**Comment by martijn-heil** [comment]
Yes, I get the exact same error on my home pc.

**Comment by panaaj** [comment]
I fixed an error in the peerDependency  declaration for signalk-worker-angular so if you run  `npm i signalk-worker-angular --save-dev` that should fix it.

**Comment by panaaj** [comment]
Is this still an issue for you or can this be closed?

**Comment by martijn-heil** [comment]
Still get errors, but this time if you `--force` it at least continues building after spitting out some warnings.
Below is the output given when doing exactly as you suggested.
```
$ git clone https://github.com/SignalK/freeboard-sk/
$ cd freeboard-sk
$ npm i signalk-worker-angular --save-dev
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @signalk/freeboard-sk@1.18.2
npm ERR! Found: jasmine-core@3.6.0
npm ERR! node_modules/jasmine-core
npm ERR!   dev jasmine-core@"~3.6.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.8" from karma-jasmine-html-reporter@1.7.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR!   dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/martijn/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/martijn/.npm/_logs/2021-09-28T16_20_32_261Z-debug.log
```
