### ISSUE TITLE
Bug: Tracks don't load

### ISSUE THREAD

**Issue by msallin** [SignalK/freeboard-sk#262]
After installing v2.13.2, the track list load.

![Image](https://github.com/user-attachments/assets/40e78fbd-7300-499e-adfc-401491010671)

![Image](https://github.com/user-attachments/assets/9c3a782f-491f-45d4-a141-885e63085057)

It works when I enter text. Thus, I assume the problem is the missing (null?) check here: https://github.com/SignalK/freeboard-sk/blob/f7c15242d3de4a119f217badb913a67b09231028/src/app/modules/skresources/components/tracks/tracklist.ts#L241

**Comment by panaaj** [comment]
Addressed in V2.14.0

**Comment by msallin** [comment]
I still get the same error. Would it help when I attach the tracks for testing (i.e. the HTTP response for tracks)?

**Comment by panaaj** [comment]
Yes that would help as I couldn't replicate the issue, I just addressed the possible null value.

**Comment by panaaj** [comment]
Fixed in v2.14.1 release

**Comment by msallin** [comment]
Tested. Works, ty!
